/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video } from "@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {Category, Intent, IntentResult, TriageResult} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type BamlCallOptions<EventsT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  env?: Record<string, string | undefined>
  events?: EventsT
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  CategorizeMessage(
      role: string,from: string,subject: string,body: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "CategorizeMessage",
        {
          "role": role,"from": from,"subject": subject,"body": body
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DetectIntent(
      user_message: string,inbox_summary: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DetectIntent",
        {
          "user_message": user_message,"inbox_summary": inbox_summary
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ReviseDraft(
      original_from: string,original_subject: string,current_draft: string,edit_instructions: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ReviseDraft",
        {
          "original_from": original_from,"original_subject": original_subject,"current_draft": current_draft,"edit_instructions": edit_instructions
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        false,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  CategorizeMessage(
      role: string,from: string,subject: string,body: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "CategorizeMessage",
        {
          "role": role,"from": from,"subject": subject,"body": body
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DetectIntent(
      user_message: string,inbox_summary: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "DetectIntent",
        {
          "user_message": user_message,"inbox_summary": inbox_summary
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ReviseDraft(
      original_from: string,original_subject: string,current_draft: string,edit_instructions: string,
      __baml_options__?: BamlCallOptions<never>
  ): HTTPRequest {
    try {
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return this.runtime.buildRequestSync(
        "ReviseDraft",
        {
          "original_from": original_from,"original_subject": original_subject,"current_draft": current_draft,"edit_instructions": edit_instructions
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __clientRegistry__,
        true,
        __env__,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}